-- DROP TABLE IF EXISTS "accounts";

 CREATE TABLE "accounts" (
     "id" INT GENERATED BY DEFAULT AS IDENTITY,
     "name" VARCHAR(100) NOT NULL,
     "balance" DEC(15,2) NOT NULL,
     PRIMARY KEY("id")
 );

 INSERT INTO "accounts"("name", "balance") VALUES('Bob', 10000);

 SELECT * FROM accounts;

 BEGIN; --start of the transation

 INSERT INTO "accounts"("name", "balance") VALUES('Jack', 0);

 COMMIT; --end of the transaction

 SELECT * FROM accounts;

-- ========================================
-- Create a transaction which debits 500 from the account balance for account 2 and credit this to account 3
-- ========================================

 BEGIN;

 UPDATE accounts SET "balance" = "balance"-500 WHERE "id"=2;

 UPDATE accounts SET "balance" = "balance"+500 WHERE "id"=3;

 COMMIT;

-- ========================================

 SELECT * FROM accounts;

-- ========================================
 				-- TRIGGERS
-- ========================================

 CREATE FUNCTION addFiveDollars() RETURNS TRIGGER AS
 $$
 BEGIN
 	UPDATE accounts SET "balance" = "balance"+5;
 END;
 $$ LANGUAGE plpgsql;


 CREATE TRIGGER triggerFiveDollarBonus AFTER UPDATE ON accounts
 FOR EACH ROW EXECUTE PROCEDURE addFiveDollars();


 UPDATE accounts SET "name" = 'Bob New' WHERE "id"=1;

 SELECT * FROM accounts;